### ISSUE TITLE
Support immutable coordinates

### ISSUE THREAD

**Issue by mbway** [chris48s/geojson-rewind#7]
When generating geojson geometry from shapely the coordinates are tuples and so geojson_rewind fails when it tries to modify the  coordinates

```python
from shapely.geometry import Polygon, mapping
import geojson_rewind

p = Polygon([(0, 0), (1, 1), (1, 0)])

data = mapping(p)
print(data)

data = geojson_rewind.rewind(data)
print(data)
```

```
{'type': 'Polygon', 'coordinates': (((0.0, 0.0), (1.0, 1.0), (1.0, 0.0), (0.0, 0.0)),)}
Traceback (most recent call last):
  File "rewind.py", line 9, in <module>
    data = geojson_rewind.rewind(data)
  File "/.../python3.7/site-packages/geojson_rewind/rewind.py", line 15, in rewind
    return _rewind(gj, rfc7946)
  File "/.../python3.7/site-packages/geojson_rewind/rewind.py", line 31, in _rewind
    return correct(gj, rfc7946)
  File "/.../python3.7/site-packages/geojson_rewind/rewind.py", line 36, in correct
    feature['coordinates'] = correctRings(feature['coordinates'], rfc7946)
  File "/.../python3.7/site-packages/geojson_rewind/rewind.py", line 49, in correctRings
    rings[0] = wind(rings[0], clockwise)
TypeError: 'tuple' object does not support item assignment
``

**Comment by chris48s** [comment]
Quick solution - dump it to JSON, which will convert the tuples to js arrays

```py
import json
from shapely.geometry import Polygon, mapping
import geojson_rewind

p = Polygon([(0, 0), (1, 1), (1, 0)])

data = mapping(p)
print(data)

data = geojson_rewind.rewind(json.dumps(data))
print(data)
```

if you want a python dict as output rather than a JSON string, you can `json.loads()` it again.

```py
data = geojson_rewind.rewind(json.loads(json.dumps(data)))
print(data)
```

or

```py
data = geojson_rewind.rewind(json.dumps(data))
print(json.loads(data))
```

would both work.

**Comment by mbway** [comment]
thanks, I had the same idea as a workaround. Just letting you know about this situation in case you want to support it properly
